# Xor resolver using neural network

this is a simple `xor` solver using neural network from scrab

![](https://i.ytimg.com/vi/yTFc7uCZG5k/maxresdefault.jpg)


![](https://i.ytimg.com/vi/kNPGXgzxoHw/maxresdefault.jpg)

![](https://www.researchgate.net/profile/Medhat_Moussa/publication/228939274/figure/fig1/AS:393876184551431@1470918808455/Topology-of-ANN-used-to-solve-logic-XOR-problem.png)

![](https://cdn-images-1.medium.com/max/1600/1*qA_APGgbbh0QfRNsRyMaJg.png)


In [1]:
import numpy as np

In [2]:
# define the inputs

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([0, 1, 1, 0]).T

print("Input X:\n \n{0}\n\n".format(X))
print("Output Y:\n \n{0}".format(Y))

Input X:
 
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


Output Y:
 
[0 1 1 0]


In [3]:
# define hypepramaters

m, n = X.shape
hidden_size = 2
learning_rate = 1
number_iteration = 1000

weights_1 = np.random.random( (n + 1 , hidden_size))
weights_2 = np.random.random( (hidden_size + 1, 1))

print("Our input is matrix with {0} rows and {1} columns.".format(m, n))
print("size of the hidden layer is {0}".format(hidden_size))
print("Leanring rate is {0}".format(learning_rate))  

print("\nInitial weights for layer 1 are:\n{0}".format(weights_1))
print("\nInitial weights for layer 2 are:\n{0}".format(weights_2))

Our input is matrix with 4 rows and 2 columns.
size of the hidden layer is 2
Leanring rate is 1

Initial weights for layer 1 are:
[[ 0.70226723  0.90029796]
 [ 0.76050628  0.71859573]
 [ 0.19187847  0.28666266]]

Initial weights for layer 2 are:
[[ 0.47421091]
 [ 0.0243439 ]
 [ 0.877824  ]]


In [4]:
# define sigmoid

def sigmoid(x):
    return 1 / (1 + np.exp(x))

In [5]:
def sigmoid_grad(x):
    y = sigmoid(x)
    
    return y * (1 - y)

In [13]:
def feed_forward(X, weights_1, weights_2):
    X_bias_1 = np.c_[np.ones(X.shape[0]), X]
    
    results_1 = X_bias_1.dot(weights_1)
    
    activate_values_1 = sigmoid(results_1)
    
    X_bias_2 =  np.c_[np.ones(X.shape[0]), results_1]
    
    results_2 = X_bias_2.dot(weights_2)
    
    activate_values_2 = sigmoid(results_2)
    
    return X_bias_1, results_1, activate_values_1, X_bias_2, results_2, activate_values_2

In [11]:
X_bias_1, results_1, activate_values_1,  X_bias_2, results_2, activate_values_2   = feed_forward(X, weights_1, weights_2)

print("input with bias of layer 1: \n {0}\n".format(X_bias_1))
print("results of the layer 1 : \n {0}\n".format(results_1))
print("results of the layer 1 activate function: \n {0}\n".format(activate_values_1))

print("input with bias of layer 2: \n {0}\n".format(X_bias_2))
print("results of the layer 2 : \n {0}\n\n".format(results_2))
print("results of the layer 2 activate function: \n {0}\n\n".format(activate_values_2))

input with bias of layer 1: 
 [[ 1.  0.  0.]
 [ 1.  0.  1.]
 [ 1.  1.  0.]
 [ 1.  1.  1.]]

results of the layer 1 : 
 [[ 0.70226723  0.90029796]
 [ 0.8941457   1.18696062]
 [ 1.4627735   1.61889369]
 [ 1.65465198  1.90555635]]

results of the layer 1 activate function: 
 [[ 0.33130975  0.28898927]
 [ 0.29025504  0.23380297]
 [ 0.18804349  0.1653575 ]
 [ 0.16048121  0.1294809 ]]

input with bias of layer 2: 
 [[ 1.          0.70226723  0.90029796]
 [ 1.          0.8941457   1.18696062]
 [ 1.          1.4627735   1.61889369]
 [ 1.          1.65465198  1.90555635]]

results of the layer 2 : 
 [[ 1.28160998]
 [ 1.53792042]
 [ 1.93092425]
 [ 2.18723468]]


results of the layer 2 activate function: 
 [[ 0.21727629]
 [ 0.17683779]
 [ 0.12664832]
 [ 0.10090269]]




In [22]:
def back_propagation(X, Y, weights_1, weights_2, lraning_rate, number_iteration):
    
    current_weights_1 = weights_1
    current_weights_2 = weights_2
    errors_graph = np.array([])
    
    for i in range(number_iteration):
        x1, z1, alpha1, x2, z2, alpha2 = feed_forward(
            X,
            current_weights_1,
            current_weights_2
        )
        # loss fn = MSE
        t = np.array([Y]).T
        
        layer_2_delta = (alpha2 - t)*(alpha2*(1-alpha2))
        
        print(layer_2_delta)
        print(current_weights_1)
        
        layer_1_delta = layer_2_delta.dot(current_weights_1.T) * (alpha1 * (1-alpha1))
        
        current_weights_2 -= (lraning_rate * alpha1.T.dot(layer_2_delta))
        current_weights_1 -= (lraning_rate * X.T.dot(layer_1_delta))
        
    return current_weights_1, current_weights_2, errors_graph

In [23]:
final_weights_1, final_wights_2, errors_graph = back_propagation(
    X,
    Y,
    weights_1,
    weights_2,
    learning_rate,
    number_iteration
)


print("the errors_graph: \n {0}\n".format(errors_graph))
print("the final weights of layer 1: \n {0}\n".format(final_weights_1))
print("the final weights of layer 2: \n {0}\n".format(final_wights_2))


_, _, _, _, predicted_values = feed_forward(X, final_weights_1, final_wights_2)

[[ 0.03695159]
 [-0.11982458]
 [-0.09660014]
 [ 0.00915403]]
[[ 0.70226723  0.90029796]
 [ 0.76050628  0.71859573]
 [ 0.19187847  0.28666266]]


ValueError: shapes (4,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

![](https://chrisjmccormick.files.wordpress.com/2014/03/gradientdescentofmsetable.png)
[https://www.slideshare.net/Jboulie/ann-preso-draft](https://www.slideshare.net/Jboulie/ann-preso-draft)

[http://mccormickml.com/2014/03/04/gradient-descent-derivation/](http://mccormickml.com/2014/03/04/gradient-descent-derivation/)

[https://iamtrask.github.io/2015/07/27/python-network-part2/](https://iamtrask.github.io/2015/07/27/python-network-part2/)