# Xor resolver using neural network

this is a simple `xor` solver using neural network from scrab

![](https://i.ytimg.com/vi/yTFc7uCZG5k/maxresdefault.jpg)


![](https://i.ytimg.com/vi/kNPGXgzxoHw/maxresdefault.jpg)

![](https://www.researchgate.net/profile/Medhat_Moussa/publication/228939274/figure/fig1/AS:393876184551431@1470918808455/Topology-of-ANN-used-to-solve-logic-XOR-problem.png)

![](https://cdn-images-1.medium.com/max/1600/1*qA_APGgbbh0QfRNsRyMaJg.png)


In [2]:
import numpy as np

In [3]:
# define the inputs

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([0, 1, 1, 0]).T

print("Input X:\n \n{0}\n\n".format(X))
print("Output Y:\n \n{0}".format(Y))

Input X:
 
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


Output Y:
 
[0 1 1 0]


In [4]:
# define hypepramaters

m, n = X.shape
hidden_size = 2
learning_rate = 1
number_iteration = 1000

weights_1 = np.random.random( (n + 1 , hidden_size))
weights_2 = np.random.random( (hidden_size + 1, 1))

print("Our input is matrix with {0} rows and {1} columns.".format(m, n))
print("size of the hidden layer is {0}".format(hidden_size))
print("Leanring rate is {0}".format(learning_rate))  

print("\nInitial weights for layer 1 are:\n{0}".format(weights_1))
print("\nInitial weights for layer 2 are:\n{0}".format(weights_2))

Our input is matrix with 4 rows and 2 columns.
size of the hidden layer is 2
Leanring rate is 1

Initial weights for layer 1 are:
[[ 0.31494747  0.51661395]
 [ 0.60902069  0.40237811]
 [ 0.24663124  0.72622975]]

Initial weights for layer 2 are:
[[ 0.51746877]
 [ 0.23014433]
 [ 0.54451938]]


In [5]:
# define sigmoid

def sigmoid(x):
    return 1 / (1 + np.exp(x))

In [6]:
def sigmoid_grad(x):
    y = sigmoid(x)
    
    return y * (1 - y)

In [7]:
def feed_forward(X, weights_1, weights_2):
    X_bias_1 = np.c_[np.ones(X.shape[0]), X]
    
    results_1 = X_bias_1.dot(weights_1)
    
    X_bias_2 =  np.c_[np.ones(X.shape[0]), results_1]
    
    results_2 = X_bias_2.dot(weights_2)
    
    activate_values = sigmoid(results_2)
    
    return X_bias_1, results_1, X_bias_2, results_2, activate_values

In [8]:
X_bias_1, results_1, X_bias_2, results_2, activate_values   = feed_forward(X, weights_1, weights_2)

print("input with bias of layer 1: \n {0}\n".format(X_bias_1))
print("results of the layer 1 : \n {0}\n\n".format(results_1))

print("input with bias of layer 2: \n {0}\n".format(X_bias_2))
print("results of the layer 2 : \n {0}\n\n".format(results_2))

print("results of the activate function: \n {0}".format(activate_values))

input with bias of layer 1: 
 [[ 1.  0.  0.]
 [ 1.  0.  1.]
 [ 1.  1.  0.]
 [ 1.  1.  1.]]

results of the layer 1 : 
 [[ 0.31494747  0.51661395]
 [ 0.56157871  1.2428437 ]
 [ 0.92396816  0.91899206]
 [ 1.1705994   1.64522181]]


input with bias of layer 2: 
 [[ 1.          0.31494747  0.51661395]
 [ 1.          0.56157871  1.2428437 ]
 [ 1.          0.92396816  0.91899206]
 [ 1.          1.1705994   1.64522181]]

results of the layer 2 : 
 [[ 0.87125845]
 [ 1.3234654 ]
 [ 1.23052378]
 [ 1.68273073]]


results of the activate function: 
 [[ 0.29499251]
 [ 0.21024232]
 [ 0.22608977]
 [ 0.15673421]]


In [63]:
def back_propagation(X, Y, weights_1, weights_2, lraning_rate, number_iteration):
    
    current_weights_1 = weights_1
    current_weights_2 = weights_2
    errors_graph = np.array([])
    
    for i in range(number_iteration):
        X_bias_1, results_1, X_bias_2, results_2, activate_values = feed_forward(
            X,
            current_weights_1,
            current_weights_2
        )
        
        error = np.subtract(np.array([Y]).T, activate_values)
        
        print(error)
        
        delta_2 = error.dot(weights_2)
        
        current_weights_2 += lraning_rate * X_bias_2.T.dot(current_weights_2)
        current_weights_1 += lraning_rate * X_bias_1.T.dot(current_weights_1)
        
    return current_weights_1, current_weights_2, errors_graph

In [64]:
final_weights_1, final_wights_2, errors_graph = back_propagation(
    X,
    Y,
    weights_1,
    weights_2,
    learning_rate,
    number_iteration
)


print("the errors_graph: \n {0}\n".format(errors_graph))
print("the final weights of layer 1: \n {0}\n".format(final_weights_1))
print("the final weights of layer 2: \n {0}\n".format(final_wights_2))


_, _, _, _, predicted_values = feed_forward(X, final_weights_1, final_wights_2)

[[-0.29499251]
 [ 0.78975768]
 [ 0.77391023]
 [-0.15673421]]


ValueError: shapes (4,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)