# Xor resolver using neural network

this is a simple `xor` solver using neural network from scrab

![](https://i.ytimg.com/vi/yTFc7uCZG5k/maxresdefault.jpg)


![](https://i.ytimg.com/vi/kNPGXgzxoHw/maxresdefault.jpg)

![](https://www.researchgate.net/profile/Medhat_Moussa/publication/228939274/figure/fig1/AS:393876184551431@1470918808455/Topology-of-ANN-used-to-solve-logic-XOR-problem.png)

![](https://cdn-images-1.medium.com/max/1600/1*qA_APGgbbh0QfRNsRyMaJg.png)


In [1]:
import numpy as np

In [2]:
# define the inputs

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([0, 1, 1, 0]).T

print("Input X:\n \n{0}\n\n".format(X))
print("Output Y:\n \n{0}".format(Y))

Input X:
 
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


Output Y:
 
[0 1 1 0]


In [3]:
# define hypepramaters

m, n = X.shape
hidden_size = 2
learning_rate = 1
number_iteration = 1000

weights_1 = np.random.random( (n + 1 , hidden_size))
weights_2 = np.random.random( (hidden_size + 1, 1))

print("Our input is matrix with {0} rows and {1} columns.".format(m, n))
print("size of the hidden layer is {0}".format(hidden_size))
print("Leanring rate is {0}".format(learning_rate))  

print("\nInitial weights for layer 1 are:\n{0}".format(weights_1))

print("\nInitial weights for layer 2 are:\n{0}".format(weights_2))


Our input is matrix with 4 rows and 2 columns.
size of the hidden layer is 2
Leanring rate is 1

Initial weights for layer 1 are:
[[ 0.41253702  0.43935284]
 [ 0.30141033  0.19264487]
 [ 0.29827723  0.82100651]]

Initial weights for layer 2 are:
[[ 0.80395794]
 [ 0.61477662]
 [ 0.97675858]]


In [4]:
# define sigmoid

def sigmoid(x):
    return 1 / (1 + np.exp(x))

In [5]:
def sigmoid_grad(y):
    return y * (1 - y)

In [6]:
def feed_forward(X, weights_1, weights_2):
    X_bias_1 = np.c_[np.ones(X.shape[0]), X]
    
    results_1 = X_bias_1.dot(weights_1)
    
    activate_values_1 = sigmoid(results_1)
    
    X_bias_2 =  np.c_[np.ones(X.shape[0]), results_1]
    
    results_2 = X_bias_2.dot(weights_2)
    
    activate_values_2 = sigmoid(results_2)
    
    return results_1, activate_values_1, results_2, activate_values_2

In [7]:
results_1, activate_values_1, results_2, activate_values_2   = feed_forward(X, weights_1, weights_2)

print("results of the layer 1 : \n {0}\n".format(results_1))
print("results of the layer 1 activate function: \n {0}\n".format(activate_values_1))

print("results of the layer 2 : \n {0}\n\n".format(results_2))
print("results of the layer 2 activate function: \n {0}\n\n".format(activate_values_2))

results of the layer 1 : 
 [[ 0.41253702  0.43935284]
 [ 0.71081425  1.26035935]
 [ 0.71394735  0.63199771]
 [ 1.01222457  1.45300422]]

results of the layer 1 activate function: 
 [[ 0.39830395  0.39189519]
 [ 0.32941895  0.22091204]
 [ 0.32872721  0.3470577 ]
 [ 0.26654472  0.18953964]]

results of the layer 2 : 
 [[ 1.48671771]
 [ 2.47201672]
 [ 1.86018526]
 [ 2.84548428]]


results of the layer 2 activate function: 
 [[ 0.18441489]
 [ 0.07784334]
 [ 0.13468146]
 [ 0.05491521]]




In [24]:
def back_propagation(X, Y, weights_1, weights_2, lraning_rate, number_iteration):
    
    current_weights_1 = weights_1
    current_weights_2 = weights_2
    
    for i in range(number_iteration):
        h1, alpha1, h2, alpha2 = feed_forward(
            X,
            current_weights_1,
            current_weights_2
        )
        # loss fn = MSE
        t = np.array([Y]).T
        
        e2 = (h2 - t) / X.shape[1]
        
        dw2 = np.dot(sigmoid_grad(alpha2), e2.T)
        
        e1 = np.dot(dw2, current_weights_1)
        
        dw1 = np.dot(sigmoid_grad(alpha), e1.T )
        
        layer1_adjustment = X.T.dot(dw1)
        layer2_adjustment = Y.T.dot(dw2)
        
        current_weights_2 += (lraning_rate * layer2_adjustment)
        current_weights_1 += (lraning_rate * layer1_adjustment)
        
    return current_weights_1, current_weights_2

In [25]:
final_weights_1, final_wights_2 = back_propagation(
    X,
    Y,
    weights_1,
    weights_2,
    learning_rate,
    number_iteration
)


print("the errors_graph: \n {0}\n".format(errors_graph))
print("the final weights of layer 1: \n {0}\n".format(final_weights_1))
print("the final weights of layer 2: \n {0}\n".format(final_wights_2))


_, _, _, _, predicted_values = feed_forward(X, final_weights_1, final_wights_2)

ValueError: shapes (4,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

![](https://chrisjmccormick.files.wordpress.com/2014/03/gradientdescentofmsetable.png)
[https://www.slideshare.net/Jboulie/ann-preso-draft](https://www.slideshare.net/Jboulie/ann-preso-draft)

[http://mccormickml.com/2014/03/04/gradient-descent-derivation/](http://mccormickml.com/2014/03/04/gradient-descent-derivation/)

[https://iamtrask.github.io/2015/07/27/python-network-part2/](https://iamtrask.github.io/2015/07/27/python-network-part2/)